name: istravUp
on:
  workflow_dispatch:
    inputs:
      stackId:
        description: 'Stack Id'
        required: true
        default: 'prod'
      planId:
        description: 'Plan Id'
        required: true
        default: 'tardigrade'
      AMQP_URI:
        description: 'AMQP_URI'
        required: true
        default: ''
      MONGODB_URI:
        description: 'MONGODB_URI'
        required: true
        default: ''
      POSTGRESQL_URI:
        description: 'POSTGRESQL_URI'
        required: true
        default: ''
      SECRET:
        description: 'SECRET'
        required: true
        default: ''
      AWS_ACCESS_KEY:
        description: 'AWS_ACCESS_KEY'
        required: true
        default: ''
      AWS_SECRET_KEY:
        description: 'AWS_SECRET_KEY'
        required: true
        default: ''
jobs:
  up:
    name: Update
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./istrav
    steps:
      - uses: actions/checkout@v2
      - name: Install pulumi
        uses: pulumi/action-install-pulumi-cli@v1.0.1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install 
        run: npm install
      - name: Configure
        run: | 
          pulumi stack select ${{ github.event.inputs.stackId }}
          pulumi config set aws:region ${{ github.event.inputs.regionId }} --plaintext
          pulumi config set istrav:plan ${{ github.event.inputs.planId }} --plaintext
          pulumi config set istrav:AMQP_URI ${{ github.event.inputs.AMQP_URI }} --secret
          pulumi config set istrav:MONGODB_URI ${{ github.event.inputs.MONGODB_URI }} --secret
          pulumi config set istrav:POSTGRESQL_URI ${{ github.event.inputs.POSTGRESQL_URI }} --secret
          pulumi config set istrav:SECRET ${{ github.event.inputs.SECRET }} --secret
          pulumi config set istrav:AWS_ACCESS_KEY ${{ github.event.inputs.AWS_ACCESS_KEY }} --secret
          pulumi config set istrav:AWS_SECRET_KEY ${{ github.event.inputs.AWS_SECRET_KEY }} --secret
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - uses: pulumi/actions@v2
        with:
          work-dir: ./istrav
          command: up
          stack-name: ${{ github.event.inputs.stackId }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
          LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
