name: istravUp
on:
  workflow_dispatch:
    inputs:
      stackId:
        description: 'Stack Id'
        required: true
        default: 'prod'
      regionId:
        description: 'Region Id'
        required: true
        default: 'us-east-1'
      instanceCount:
        description: 'Instance Count'
        required: true
        default: 1
      instanceType:
        description: 'Instance Type'
        required: true
        default: 't2.micro'
jobs:
  up:
    name: Update
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./istrav
    steps:
      - uses: actions/checkout@v2
      - name: Install pulumi
        uses: pulumi/action-install-pulumi-cli@v1.0.1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install 
        run: npm install
      - name: Configure
        run: | 
          pulumi stack select ${{ github.event.inputs.stackId }}
          pulumi config set istrav:region ${{ github.event.inputs.regionId }}
          pulumi config set istrav:instanceCount ${{ github.event.inputs.instanceCount }}
          pulumi config set istrav:instanceType ${{ github.event.inputs.instanceType }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - uses: pulumi/actions@v2
        with:
          work-dir: ./istrav
          command: up
          stack-name: ${{ github.event.inputs.stackId }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
          LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
