name: istravInit
on:
  workflow_dispatch:
    inputs:
      stackId:
        description: 'Stack Id'     
        required: true
        default: 'istrav.com'
jobs:
  init:
    name: Install
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./istrav
    steps:
      - uses: actions/checkout@v2
      - name: Install pulumi
        uses: pulumi/action-install-pulumi-cli@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install 
        run: npm install
      - name: Init
        run: pulumi stack init ${{ github.event.inputs.stackId }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
          LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
