name: istravRemove
on:
  workflow_dispatch:
    inputs:
      stackId:
        description: 'Stack Id'     
        required: true
        default: 'prod'
jobs:
  remove:
    name: Delete
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./istrav
    steps:
      - uses: actions/checkout@v2
      - name: Install pulumi
        uses: pulumi/action-install-pulumi-cli@v1.0.1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install 
        run: npm install
      - name: Delete
        run: pulumi stack rm ${{ github.event.inputs.stackId }} -y
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
