name: istravDestory
on: 
  workflow_dispatch:
    inputs:
      stackId:
        description: 'Stack Id'     
        required: true
        default: 'prod'
      regionId:
        description: 'Region Id'     
        required: true
        default: 'us-east-1'
jobs:
  destroy:
    name: Delete
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./istrav
    steps:
      - uses: actions/checkout@v2
      - name: Install pulumi
        uses: pulumi/action-install-pulumi-cli@v1.0.1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install 
        run: npm install
      - uses: pulumi/actions@v2
        with:
          work-dir: ./istrav
          command: destroy
          stack-name: ${{ github.event.inputs.stackId }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
          LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ github.event.inputs.regionId }}
