name: istravUp
on:
  workflow_dispatch:
    inputs:
      stackId:
        description: 'Stack Id'     
        required: true
        default: 'prod'
jobs:
  up:
    name: Update
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./istrav
    steps:
      - uses: actions/checkout@v2
      - name: Install pulumi
        uses: pulumi/action-install-pulumi-cli@v1.0.1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install 
        run: npm install
      - uses: pulumi/actions@v2
        with:
          work-dir: ./istrav
          command: up
          stack-name: ${{ github.event.inputs.stackId }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
