name: istravUp
on:
  workflow_dispatch:
    inputs:
      stackId:
        description: 'Stack Id'
        required: true
        default: 'istrav.com'
      planId:
        description: 'Plan Id'
        required: true
        default: 'tardigrade'
      ACK_DOMAIN:
        description: 'ACK_DOMAIN'
        required: true
        default: 'hacktracks.org'
      HEADLESS_DOMAIN:
        description: 'HEADLESS_DOMAIN'
        required: true
        default: 'farmerless.com'
      POSTGRESQL_URI:
        description: 'POSTGRESQL_URI'
        required: true
        default: ''
      SECRET:
        description: 'SECRET'
        required: true
        default: ''
      AWS_ACCESS_KEY:
        description: 'AWS_ACCESS_KEY'
        required: true
        default: ''
      AWS_SECRET_KEY:
        description: 'AWS_SECRET_KEY'
        required: true
        default: ''
jobs:
  up:
    name: Update
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./istrav
    steps:
      - uses: actions/checkout@v2
      - name: Install pulumi
        uses: pulumi/action-install-pulumi-cli@v1.0.1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install 
        run: npm install
      - name: Configure
        run: | 
          pulumi stack select ${{ github.event.inputs.stackId }}
          pulumi config set --plaintext istrav:planId ${{ github.event.inputs.planId }}
          pulumi config set --plaintext istrav:stackId ${{ github.event.inputs.stackId }}
          pulumi config set --plaintext istrav:ACK_DOMAIN ${{ github.event.inputs.ACK_DOMAIN }}
          pulumi config set --plaintext istrav:HEADLESS_DOMAIN ${{ github.event.inputs.HEADLESS_DOMAIN }}
          pulumi config set --plaintext istrav:POSTGRESQL_URI ${{ github.event.inputs.POSTGRESQL_URI }}
          pulumi config set --plaintext istrav:SECRET ${{ github.event.inputs.SECRET }}
          pulumi config set --plaintext istrav:AWS_ACCESS_KEY ${{ github.event.inputs.AWS_ACCESS_KEY }}
          pulumi config set --plaintext istrav:AWS_SECRET_KEY ${{ github.event.inputs.AWS_SECRET_KEY }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - uses: pulumi/actions@v2
        with:
          work-dir: ./istrav
          command: up
          stack-name: ${{ github.event.inputs.stackId }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
          LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
